"""Sample strategy definitions and metadata."""

SAMPLE_STRATEGIES: list[dict] = [
    {
        "name": "EMA Cross",
        "description": "Buy when fast EMA crosses above slow EMA, sell on cross below.",
        "strategy_type": "ema_cross",
        "symbols": ["EURUSD", "GBPUSD", "XAUUSD"],
        "timeframes": ["H1"],
        "indicators": ["ema"],
        "entry_conditions": {
            "type": "ema_cross",
            "params": {"fast_period": 9, "slow_period": 21},
        },
        "stop_loss_pips": 20,
        "take_profit_pips": 40,
        "max_risk_percent": 1.0,
        "max_trades": 3,
        "magic_number": 100001,
    },
    {
        "name": "EMA + RSI Filter",
        "description": "EMA cross confirmed by RSI — avoids overbought buys and oversold sells.",
        "strategy_type": "ema_rsi",
        "symbols": ["EURUSD", "GBPUSD"],
        "timeframes": ["H1"],
        "indicators": ["ema", "rsi"],
        "entry_conditions": {
            "type": "ema_rsi",
            "params": {
                "fast_period": 9,
                "slow_period": 21,
                "rsi_period": 14,
                "rsi_overbought": 70,
                "rsi_oversold": 30,
            },
        },
        "stop_loss_pips": 25,
        "take_profit_pips": 50,
        "max_risk_percent": 1.0,
        "max_trades": 2,
        "magic_number": 100002,
    },
    {
        "name": "MACD Trend",
        "description": "Trade in direction of MACD histogram and signal line crossover.",
        "strategy_type": "macd_trend",
        "symbols": ["EURUSD", "USDJPY", "XAUUSD"],
        "timeframes": ["H1"],
        "indicators": ["macd", "atr"],
        "entry_conditions": {
            "type": "macd_trend",
            "params": {"fast": 12, "slow": 26, "signal": 9, "atr_period": 14},
        },
        "stop_loss_pips": 30,
        "take_profit_pips": 60,
        "max_risk_percent": 1.0,
        "max_trades": 3,
        "magic_number": 100003,
    },
    {
        "name": "Breakout",
        "description": "Enter when price breaks above/below recent range high/low.",
        "strategy_type": "breakout",
        "symbols": ["XAUUSD", "BTCUSD", "US30"],
        "timeframes": ["H1"],
        "indicators": ["atr"],
        "entry_conditions": {
            "type": "breakout",
            "params": {"lookback": 20, "atr_multiplier": 1.5},
        },
        "stop_loss_pips": 40,
        "take_profit_pips": 80,
        "max_risk_percent": 0.75,
        "max_trades": 2,
        "magic_number": 100004,
    },
    {
        "name": "Support & Resistance",
        "description": "Bounce trades near Bollinger Bands and pivot levels.",
        "strategy_type": "support_resistance",
        "symbols": ["EURUSD", "XAUUSD"],
        "timeframes": ["H1"],
        "indicators": ["bbands", "pivots", "rsi"],
        "entry_conditions": {
            "type": "support_resistance",
            "params": {"bb_period": 20, "rsi_period": 14},
        },
        "stop_loss_pips": 20,
        "take_profit_pips": 40,
        "max_risk_percent": 1.0,
        "max_trades": 3,
        "magic_number": 100005,
    },
    {
        "name": "Pullback",
        "description": "Enter on pullback to EMA in established trend with RSI confirmation.",
        "strategy_type": "pullback",
        "symbols": ["EURUSD", "GBPUSD", "AUDUSD"],
        "timeframes": ["H1"],
        "indicators": ["ema", "rsi", "adx"],
        "entry_conditions": {
            "type": "pullback",
            "params": {
                "ema_period": 50,
                "rsi_period": 14,
                "adx_period": 14,
                "adx_min": 20,
                "rsi_pullback_low": 40,
                "rsi_pullback_high": 60,
            },
        },
        "stop_loss_pips": 25,
        "take_profit_pips": 50,
        "max_risk_percent": 1.0,
        "max_trades": 2,
        "magic_number": 100006,
    },
    {
        "name": "Scalping",
        "description": "Fast EMA cross on M5 with tight ATR-based stops.",
        "strategy_type": "scalping",
        "symbols": ["EURUSD", "GBPUSD"],
        "timeframes": ["M5"],
        "indicators": ["ema", "atr", "rsi"],
        "entry_conditions": {
            "type": "scalping",
            "params": {
                "fast_period": 5,
                "slow_period": 13,
                "atr_period": 14,
                "rsi_period": 14,
                "max_atr_ratio": 0.001,
            },
        },
        "stop_loss_pips": 10,
        "take_profit_pips": 15,
        "max_risk_percent": 0.5,
        "max_trades": 1,
        "magic_number": 100007,
    },
    {
        "name": "Swing Trading",
        "description": "Trend + pattern confirmation for multi-hour holds.",
        "strategy_type": "swing",
        "symbols": ["XAUUSD", "EURUSD", "NAS100"],
        "timeframes": ["H4"],
        "indicators": ["ema", "rsi", "macd"],
        "entry_conditions": {
            "type": "swing",
            "params": {
                "ema_period": 50,
                "rsi_period": 14,
                "pattern_categories": ["candlestick"],
            },
        },
        "stop_loss_pips": 50,
        "take_profit_pips": 100,
        "max_risk_percent": 1.0,
        "max_trades": 2,
        "magic_number": 100008,
    },
]

STRATEGY_TYPES = {s["strategy_type"]: s for s in SAMPLE_STRATEGIES}
